name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: paarmatthias
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Web Image
      run: |
        docker build -t ghcr.io/paarmatthias/assignment-3-web:latest ./app
        docker push ghcr.io/paarmatthias/assignment-3-web:latest

    - name: Build and Push Redis Image
      run: |
        docker build -t ghcr.io/paarmatthias/assignment-3-redis:latest ./redis
        docker push ghcr.io/paarmatthias/assignment-3-redis:latest
